### ISSUE TITLE
Error during authorize

### ISSUE THREAD

**Issue by romeltanady** [text-to-cards/text-to-cards#4]
Add Power-Up Text to Cards
Button Text to Cards appeared beside button Butler
Click on button Text to Cards
Prompt for Autorize Text to Cards
Click on buttom Yeah, baby!
Open a popup with Error Invalid return_url

below is the popup url
https://trello.com/1/authorize?name=Text%20to%20Cards&key=14d27ba2a1d4d5160e8eaab9c3cfcf2f&expiration=never&scope=read%2Cwrite&callback_method=fragment&response_type=fragment&return_url=https%3A%2F%2Ftext-to-cards.netlify.app%2Flogin.html%23%257B%2522secret%2522%253A%2522D0ITzq8xFIK0wdowzH9T8mtKzyzLJX8pv2P0pI9fgN7Z2CHfcmY0AZWVyWnDc7P0%2522%252C%2522context%2522%253A%257B%2522version%2522%253A%2522build-5023%2522%252C%2522member%2522%253A%25225eaa7ff5571880386fe727a6%2522%252C%2522permissions%2522%253A%257B%2522board%2522%253A%2522write%2522%252C%2522organization%2522%253A%2522write%2522%257D%252C%2522organization%2522%253A%25225eb5196ccfab46112b471198%2522%252C%2522board%2522%253A%25225ebb80a5b0920c4be7154e80%2522%252C%2522card%2522%253Anull%252C%2522command%2522%253A%2522callback%2522%252C%2522el%2522%253A%25228l7ZLWaMwRkVWV2L%2522%257D%252C%2522locale%2522%253A%2522en-US%2522%257D

**Comment by somiandras** [comment]
Hi @romeltanady , thanks for reporting this. I'm looking into it. Probably some transient error on Trello's end.

**Comment by somiandras** [comment]
@romeltanady Turns out Netlify migrated the app to a new domain which wasn't registered at Trello as allowed origin for authentication. 

Works for me now. Closing the issue.

**Comment by romeltanady** [comment]
it works great now, thank you very much for the support.
